apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: sdewan-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYekNDQWtlZ0F3SUJBZ0lSQUkrZjUwb2dxUHRIZWhpN0Q4a1ViaGt3RFFZSktvWklodmNOQVFFTEJRQXcKRnpFVk1CTUdBMVVFQ2hNTVkyVnlkQzF0WVc1aFoyVnlNQjRYRFRJeE1ERXhOVEExTXpVME0xb1hEVEl4TURReApOVEExTXpVME0xb3dGekVWTUJNR0ExVUVDaE1NWTJWeWRDMXRZVzVoWjJWeU1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhHUk9DWXFqeGRpcmNSdG1TZHZHa2RJeFB2SmNLMGQ1dU9SY3F0YloKNEhSck1hbHcxODE5c1ZNSDdjdUROVStiRThxY3J1MXR3N3R0TGxmS1FKTE1kMWwwZitNYzZwYytwdnR3b2JlZwp6RFU1amdNQmZhMkoySVBaZFUwSi9Zek51VVVSVjgyaXVRY25xckt1YVB4Wm1RVm9SdUZDM0ZoL2NEakdDUGRxCnN6MGg1Y0s5dkt2QldwWGlWaUpNMXlzOTRxNXdHMk8wbUdjaDloWFh2VExtTTdlMHE0bzdveldqdHdBYlBVSzAKbk9WWFUva0FXWFkyU1FCREN3NkpKVGpMaWxaU21vMTZCWkxIakw0V2lLVmlNVGtHMzdsSE9VOTNXR2JITDVpcwo1N2NHSTVRbStZb0ZjQWppWVVRejdLa1VKcHVUZHBYbVgybUhNenN0MEhzOGVRSURBUUFCbzRHbE1JR2lNQTRHCkExVWREd0VCL3dRRUF3SUZvREFNQmdOVkhSTUJBZjhFQWpBQU1JR0JCZ05WSFJFRWVqQjRnaWh6WkdWM1lXNHQKZDJWaWFHOXZheTF6WlhKMmFXTmxMbk5rWlhkaGJpMXplWE4wWlcwdWMzWmpnalp6WkdWM1lXNHRkMlZpYUc5dgpheTF6WlhKMmFXTmxMbk5rWlhkaGJpMXplWE4wWlcwdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0NXeHZZMkZzCmFHOXpkSUlKTVRJM0xqQXVNQzR4TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBc2w4MzV2N2lsYlRLa2gyMjYKQmN4S05yK252d0hrOHpkbkxHdUlEV2tUME5FL2d4THMxZXNzRnQ0LzRGbHY3cUVnbC9nblVYNzFxWWpWYWZsRQpSTDhyN0pnS2dTUFVLSEpRK3NyNDhLT3JmK2lVbmQ2R0hwaUF4dk00alhScDFRQ25icTRGYXdxMWNMaWh6cENPCmJJYzUrUUpzQkZ1L2xJaXVTTjZoKzJmK3JoazFCNmN2Zm4vTGQ1cWh3UG9aWkVQeDRJYzhaSDl1cUs0Vzl2QnEKRzRUN2ZZZkl2Rk43T1VvZDA5K1JmTmRiLzMyTHBBakRvY1ZKcFBxZlJxWFJ4MjNFWFN1VmNTMlF4S3ZQQ3BKTQp0SFl0UEdYSXdxMHRvSWs2bmVwVUxuRzE4dGNtVklWSVJRaEFYTG9zMTBRMEM2UUMwTGFaa3psMVNqQzEzQ2l2CnNIczgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://localhost:9443/validate-sdewan-bucket-permission
  failurePolicy: Fail
  name: bucket-permission.kb.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - batch.sdewan.akraino.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - mwan3policies
    - mwan3rules
    - firewalldnats
    - firewallforwardings
    - firewallrules
    - firewallsnats
    - firewallzones
    - ipsechosts
    - ipsecproposals
    - ipsecsites
    - cnfservice
    - sdewanapplication
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYekNDQWtlZ0F3SUJBZ0lSQUkrZjUwb2dxUHRIZWhpN0Q4a1ViaGt3RFFZSktvWklodmNOQVFFTEJRQXcKRnpFVk1CTUdBMVVFQ2hNTVkyVnlkQzF0WVc1aFoyVnlNQjRYRFRJeE1ERXhOVEExTXpVME0xb1hEVEl4TURReApOVEExTXpVME0xb3dGekVWTUJNR0ExVUVDaE1NWTJWeWRDMXRZVzVoWjJWeU1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhHUk9DWXFqeGRpcmNSdG1TZHZHa2RJeFB2SmNLMGQ1dU9SY3F0YloKNEhSck1hbHcxODE5c1ZNSDdjdUROVStiRThxY3J1MXR3N3R0TGxmS1FKTE1kMWwwZitNYzZwYytwdnR3b2JlZwp6RFU1amdNQmZhMkoySVBaZFUwSi9Zek51VVVSVjgyaXVRY25xckt1YVB4Wm1RVm9SdUZDM0ZoL2NEakdDUGRxCnN6MGg1Y0s5dkt2QldwWGlWaUpNMXlzOTRxNXdHMk8wbUdjaDloWFh2VExtTTdlMHE0bzdveldqdHdBYlBVSzAKbk9WWFUva0FXWFkyU1FCREN3NkpKVGpMaWxaU21vMTZCWkxIakw0V2lLVmlNVGtHMzdsSE9VOTNXR2JITDVpcwo1N2NHSTVRbStZb0ZjQWppWVVRejdLa1VKcHVUZHBYbVgybUhNenN0MEhzOGVRSURBUUFCbzRHbE1JR2lNQTRHCkExVWREd0VCL3dRRUF3SUZvREFNQmdOVkhSTUJBZjhFQWpBQU1JR0JCZ05WSFJFRWVqQjRnaWh6WkdWM1lXNHQKZDJWaWFHOXZheTF6WlhKMmFXTmxMbk5rWlhkaGJpMXplWE4wWlcwdWMzWmpnalp6WkdWM1lXNHRkMlZpYUc5dgpheTF6WlhKMmFXTmxMbk5rWlhkaGJpMXplWE4wWlcwdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0NXeHZZMkZzCmFHOXpkSUlKTVRJM0xqQXVNQzR4TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBc2w4MzV2N2lsYlRLa2gyMjYKQmN4S05yK252d0hrOHpkbkxHdUlEV2tUME5FL2d4THMxZXNzRnQ0LzRGbHY3cUVnbC9nblVYNzFxWWpWYWZsRQpSTDhyN0pnS2dTUFVLSEpRK3NyNDhLT3JmK2lVbmQ2R0hwaUF4dk00alhScDFRQ25icTRGYXdxMWNMaWh6cENPCmJJYzUrUUpzQkZ1L2xJaXVTTjZoKzJmK3JoazFCNmN2Zm4vTGQ1cWh3UG9aWkVQeDRJYzhaSDl1cUs0Vzl2QnEKRzRUN2ZZZkl2Rk43T1VvZDA5K1JmTmRiLzMyTHBBakRvY1ZKcFBxZlJxWFJ4MjNFWFN1VmNTMlF4S3ZQQ3BKTQp0SFl0UEdYSXdxMHRvSWs2bmVwVUxuRzE4dGNtVklWSVJRaEFYTG9zMTBRMEM2UUMwTGFaa3psMVNqQzEzQ2l2CnNIczgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://localhost:9443/validate-label
  failurePolicy: Fail
  name: validate-label.kb.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - batch.sdewan.akraino.org
    - apps
    apiVersions:
    - v1alpha1
    - v1
    operations:
    - UPDATE
    resources:
    - deployments
    - mwan3policies
    - mwan3rules
    - firewalldnats
    - firewallforwardings
    - firewallrules
    - firewallsnats
    - firewallzones
    - ipsechosts
    - ipsecproposals
    - cnfservice
    - sdewanapplication
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
